[package]
name = "cronclearer"
description = "Making cron job outputs clearer and easier to debug."
authors = ["Micha Glave <coding@migmedia.de>"]
version = "1.0.0"
edition = "2024"

[dependencies]
tempfile = "3.17"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
